apiVersion: v1
kind: Secret
metadata:
  name: qa-stage-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }
  name: <cluster_name>
  server: <controlplane_url>
type: Opaque
