apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-qa-stage
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: infra
      server: <controlplane_url>
    # - namespace: kube-system
    #   server: <controlplane_url>
  sourceRepos:
    # Modificar para a URL do seu repositório
    - https://gitlab.com/minha_empresa/application-manifests.git
    - https://helm.releases.hashicorp.com
